-- @description hsuanice_Pro Tools Play
-- @version 0.1.0 [260413.1324]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Wrapper script replicating the Pro Tools action:
--   **Play**
--
--   ## Mapping
--   - Pro Tools equivalent : Play
--   - Reaper action        : Transport: Play
--   - Command ID           : 1007
--   - Module               : Transport
--   - Mac shortcut (PT)    : —
--   - Tags                 : Transport
--
--   ## About This Project
--   Part of the PT2Reaper project — a complete mapping of Pro Tools
--   keyboard shortcuts and actions to native REAPER equivalents.
--
--   ## Development
--   Developed with the assistance of Claude AI (Anthropic).
--
-- @changelog
--   0.1.0 [260413.1324]
--     - Initial release
--     - Maps Pro Tools "Play" to Reaper command ID 1007

reaper.Main_OnCommand(1007, 0)
