-- @description hsuanice_Pro Tools Record Half Speed
-- @version 0.1.0 [260413.1324]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Wrapper script replicating the Pro Tools action:
--   **Record Half Speed**
--
--   ## Mapping
--   - Pro Tools equivalent : Record Half Speed
--   - Reaper action        : Transport: Record (half speed)
--   - Command ID           : 40192
--   - Module               : Transport
--   - Mac shortcut (PT)    : Command + Shift + Space
--   - Tags                 : Recording, Transport
--
--   ## About This Project
--   Part of the PT2Reaper project — a complete mapping of Pro Tools
--   keyboard shortcuts and actions to native REAPER equivalents.
--
--   ## Development
--   Developed with the assistance of Claude AI (Anthropic).
--
-- @changelog
--   0.1.0 [260413.1324]
--     - Initial release
--     - Maps Pro Tools "Record Half Speed" to Reaper command ID 40192

reaper.Main_OnCommand(40192, 0)
