-- @description hsuanice_Pro Tools Zoom In Audio Vertical
-- @version 0.1.0 [260413.1324]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Wrapper script replicating the Pro Tools action:
--   **Zoom In Audio Vertical**
--
--   ## Mapping
--   - Pro Tools equivalent : Zoom In Audio Vertical
--   - Reaper action        : View: Zoom in vertical
--   - Command ID           : 40111
--   - Module               : Zoom
--   - Mac shortcut (PT)    : Command + Option + ]
--   - Tags                 : Zoom
--
--   ## About This Project
--   Part of the PT2Reaper project — a complete mapping of Pro Tools
--   keyboard shortcuts and actions to native REAPER equivalents.
--
--   ## Development
--   Developed with the assistance of Claude AI (Anthropic).
--
-- @changelog
--   0.1.0 [260413.1324]
--     - Initial release
--     - Maps Pro Tools "Zoom In Audio Vertical" to Reaper command ID 40111

reaper.Main_OnCommand(40111, 0)
