-- @description hsuanice_Pro Tools New Track
-- @version 0.1.0 [260413.1324]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Wrapper script replicating the Pro Tools action:
--   **New Track**
--
--   ## Mapping
--   - Pro Tools equivalent : New Track
--   - Reaper action        : Track: Insert new track at end of track list
--   - Command ID           : 40702
--   - Module               : Tracks
--   - Mac shortcut (PT)    : Command + Shift + N
--   - Tags                 : Track menu, Track/Playlist
--
--   ## About This Project
--   Part of the PT2Reaper project — a complete mapping of Pro Tools
--   keyboard shortcuts and actions to native REAPER equivalents.
--
--   ## Development
--   Developed with the assistance of Claude AI (Anthropic).
--
-- @changelog
--   0.1.0 [260413.1324]
--     - Initial release
--     - Maps Pro Tools "New Track" to Reaper command ID 40702

reaper.Main_OnCommand(40702, 0)
