-- @description hsuanice_Pro Tools Step Input: Half Note
-- @version 0.1.0 [260413.1324]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Stub script for the Pro Tools action:
--   **Step Input: Half Note**
--
--   ## Status
--   NOT YET IMPLEMENTED — placeholder only.
--
--   ## Details
--   - Pro Tools equivalent : Step Input: Half Note
--   - Module               : MIDI
--   - Mac shortcut (PT)    : Numpad 2
--   - Tags                 : MIDI, Recording
--
--   ## About This Project
--   Part of the PT2Reaper project — a complete mapping of Pro Tools
--   keyboard shortcuts and actions to native REAPER equivalents.
--
--   ## Development
--   Developed with the assistance of Claude AI (Anthropic).
--
-- @changelog
--   0.1.0 [260413.1324]
--     - Stub placeholder created

-- TODO: not yet mapped to a Reaper action
reaper.ShowMessageBox("Not yet implemented: Step Input: Half Note", "PT2Reaper", 0)
