-- @description hsuanice_Pro Tools Open Project
-- @version 0.1.0 [260413.1324]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Wrapper script replicating the Pro Tools action:
--   **Open Project**
--
--   ## Mapping
--   - Pro Tools equivalent : Open Project
--   - Reaper action        : File: Open project
--   - Command ID           : 40025
--   - Module               : Misc
--   - Mac shortcut (PT)    : —
--   - Tags                 : File menu
--
--   ## About This Project
--   Part of the PT2Reaper project — a complete mapping of Pro Tools
--   keyboard shortcuts and actions to native REAPER equivalents.
--
--   ## Development
--   Developed with the assistance of Claude AI (Anthropic).
--
-- @changelog
--   0.1.0 [260413.1324]
--     - Initial release
--     - Maps Pro Tools "Open Project" to Reaper command ID 40025

reaper.Main_OnCommand(40025, 0)
