-- @description hsuanice_Pro Tools Double Edit Selection
-- @version 0.1.0 [260413.1324]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Wrapper script replicating the Pro Tools action:
--   **Double Edit Selection**
--
--   ## Mapping
--   - Pro Tools equivalent : Double Edit Selection
--   - Reaper action        : View: Zoom time selection
--   - Command ID           : 40031
--   - Module               : Editing
--   - Mac shortcut (PT)    : Command + Option + Control + Shift + '
--   - Tags                 : Edit menu, Editing, Selection
--
--   ## About This Project
--   Part of the PT2Reaper project — a complete mapping of Pro Tools
--   keyboard shortcuts and actions to native REAPER equivalents.
--
--   ## Development
--   Developed with the assistance of Claude AI (Anthropic).
--
-- @changelog
--   0.1.0 [260413.1324]
--     - Initial release
--     - Maps Pro Tools "Double Edit Selection" to Reaper command ID 40031

reaper.Main_OnCommand(40031, 0)
