-- @description hsuanice_Pro Tools Abort Current Recording
-- @version 0.1.0 [260413.1324]
-- @author hsuanice
-- @link https://forum.cockos.com/showthread.php?p=2910884#post2910884
-- @about
--   # hsuanice Pro Tools Keybindings for REAPER
--
--   Wrapper script replicating the Pro Tools action:
--   **Abort Current Recording**
--
--   ## Mapping
--   - Pro Tools equivalent : Abort Current Recording
--   - Reaper action        : Transport: Abort/exit record and optionally delete recorded media
--   - Command ID           : 40020
--   - Module               : Transport
--   - Mac shortcut (PT)    : Command + Numpad Period
--   - Tags                 : Recording, Transport
--
--   ## About This Project
--   Part of the PT2Reaper project — a complete mapping of Pro Tools
--   keyboard shortcuts and actions to native REAPER equivalents.
--
--   ## Development
--   Developed with the assistance of Claude AI (Anthropic).
--
-- @changelog
--   0.1.0 [260413.1324]
--     - Initial release
--     - Maps Pro Tools "Abort Current Recording" to Reaper command ID 40020

reaper.Main_OnCommand(40020, 0)
